Repository icon-project/loopchain, pull requests merged in 2018-11, with the labels that each got.

#20 [LC-26] Edit `BlockGenerationScheduler` and logic to reset leader without status check of new leader candidates.
  loopchain/baseservice/block_generation_scheduelr.py
  loopchain/baseservice/peer_manager.py
  loopchain/blockchain/block.py
  loopchain/blockchain/blockchain.py
  loopchain/channel/channel_service.py
  loopchain/consensus/acceptor.py
  loopchain/consensus/consensus.py
  loopchain/consensus/proposer.py
  loopchain/consensus/publisher.py
  loopchain/peer/block_manager.py
  loopchain/peer/peer_outer_service.py
Labels: bug, enhancement

#21 [LC-39] add state machine for consensus
  .gitignore
  docs/8. diagram/state_machine_in_siever.wsd
  loopchain/baseservice/block_generation_scheduelr.py
  loopchain/baseservice/peer_manager.py
  loopchain/baseservice/timer_service.py
  loopchain/channel/channel_inner_service.py
  loopchain/channel/channel_service.py
  loopchain/channel/channel_statemachine.py
  loopchain/consensus/acceptor.py
  loopchain/consensus/consensus.py
  loopchain/peer/block_manager.py
  loopchain/statemachine/__init__.py
  loopchain/statemachine/statemachine.py
  requirements.txt
  testcase/unittest/test_channel_statemachine.py
  testcase/unittest/test_statemachine.py
  testcase/unittest/test_timer_service.py
Labels: enhancement

#24 [LC-33] Add `EventSystem` which has sequence.
  loopchain/channel/channel_service.py
  loopchain/consensus/acceptor.py
  loopchain/consensus/consensus.py
  loopchain/consensus/proposer.py
  loopchain/consensus/publisher.py
  loopchain/consensus/subscriber.py
  loopchain/peer/block_manager.py
  testcase/unittest/test_event_system.py
Labels: enhancement

#25 [LC-49] Feature/lc 49 leader complain by state machine and RS.
  README.md
  loopchain/baseservice/peer_manager.py
  loopchain/channel/channel_inner_service.py
  loopchain/channel/channel_service.py
  loopchain/channel/channel_statemachine.py
  loopchain/configure_default.py
  loopchain/peer/block_manager.py
  loopchain/peer/candidate_blocks.py
  loopchain/peer/consensus_base.py
  loopchain/peer/consensus_siever.py
  loopchain/peer/peer_outer_service.py
  loopchain/protos/message_code.py
  testcase/unittest/test_channel_statemachine.py
Labels: bug

#31 [LC-74] Block Version System - Bug fix
  loopchain/blockchain/blockchain.py
  loopchain/blockchain/blocks/block.py
  loopchain/blockchain/blocks/block_builder.py
  loopchain/blockchain/blocks/v0_1a/block.py
  loopchain/blockchain/blocks/v0_1a/block_builder.py
  loopchain/blockchain/blocks/v0_1a/block_serializer.py
  loopchain/peer/block_manager.py
  loopchain/peer/consensus_base.py
  loopchain/peer/consensus_siever.py
Labels: bug
